[ { QUESTION_ID: 0,
    SUB_QUESTION_ID: null,
    QUESTION_TYPE: 1,
    QUESTION_STRING: 'Check the appropriate box to identify your high school completion requirement for degree-seeking entering students',
    ANSWER_ID: 1,
    ANSWER_SET: 'Require Recommend>Neither require nor recommend>No answer ' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '8',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '9',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '10',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '11',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '13',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '14',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' },
  { QUESTION_ID: 2,
    SUB_QUESTION_ID: '19',
    QUESTION_TYPE: 4,
    QUESTION_STRING: 'Distribution of high school units required and/or recommended. (CDS C5) Specify the distribution of academic high school course units required and/or recommended of all or most degree-seeking students using Carnegie units (one unit equals one year of study or its equivalent). If you use a different system for calculating units, please convert.',
    ANSWER_ID: 2,
    ANSWER_SET: 'Units Required>Units Recommended' } ]

  
    Instead of : 'Units Required>Units Recommended' 
    [{ans:'Units Required'}, {ans:'Units Recommended'}]